version: 1.2.{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
image: Visual Studio 2019
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
build:
  project: .\src\
  verbosity: minimal
deploy:
- provider: NuGet
  api_key:
    secure: wQUdWr0VazZ6OFtSPfXgC9FN+FQwdyiN5eIhBWvMsxJDNpzJJb1nhuYCyjj4UPKu
  skip_symbols: true
  on:
    branch: master